# Default values for hw7.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: hw7-in-helm

webService:
  replicaCount: 2  
  
dbService:
  replicaCount: 1
  storageSize: 1Gi
  storageHostPath: "/home/hw7/volumes/db"
  storagePersistentVolumeName: db-storage-claim


