apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: config-map-db-options
  namespace: {{ .Values.namespace }}  
  labels:
    app: postgresdb
data:
  POSTGRES_DB: hw7db

