# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: postgresdb
  namespace: {{ .Values.namespace }}
spec:
  # Replicas for this Deployment
  replicas: {{ .Values.dbService.replicaCount }}
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
        namespace: {{ .Values.namespace }}
    spec:
      containers:
        - name: postgresdb
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: config-map-db-options
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: username     
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ .Values.dbService.storagePersistentVolumeName }}
