apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  name: {{ .Values.dbService.storagePersistentVolumeName }}
  namespace: {{ .Values.namespace }}
  labels:
    type: local
    app: postgresdb
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.dbService.storageSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.dbService.storageHostPath }} 
