apiVersion: v1
# Kind for service
kind: Service
metadata:
  name: postgresdb-service
  namespace: {{ .Values.namespace }}  
  labels:
    app: postgresdb
spec:
  type: NodePort
  ports:
    - port: 5432
#      nodePort: 32432
  selector:
    app: postgresdb
