apiVersion: v1
# define a resource for volume chain
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dbService.storagePersistentVolumeName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.dbService.storageSize }}
